# Generated by Django 4.2.6 on 2023-10-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingdata",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="buildingdata",
            name="longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="buildingdata",
            name="hasElevator",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="buildingdata",
            name="hasRamps",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="buildingdata",
            name="isElevatorWorking",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="buildingdata",
            name="numEntrances",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="buildingdata",
            name="numMotorizedEntrances",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
