# Generated by Django 4.2.6 on 2023-10-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_buildingdata_latitude_buildingdata_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingdata",
            name="hasElevator",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="buildingdata",
            name="hasRamps",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="buildingdata",
            name="isElevatorWorking",
            field=models.CharField(max_length=64),
        ),
    ]
